# Generated by Django 4.0.4 on 2022-05-18 20:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Введите наименование навыка', max_length=200, verbose_name='Навык')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Напишите ваш навык', verbose_name='Описание навыка')),
                ('candidate', models.ForeignKey(help_text='Заполняется автоматически', on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL, verbose_name='кандидат')),
                ('group', models.ForeignKey(blank=True, help_text='Выбрать навык', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='lk.skillgroup', verbose_name='Навык')),
            ],
        ),
    ]
