# Generated by Django 4.0.4 on 2022-05-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0002_candidate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidate',
            old_name='candidates',
            new_name='name',
        ),
    ]
