# Generated by Django 4.0.4 on 2022-05-20 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0004_alter_candidate_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Введите название навыка', max_length=200, verbose_name='название сообщества')),
            ],
        ),
        migrations.RemoveField(
            model_name='skill',
            name='group',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='text',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(help_text='Введите навык', max_length=200, null=True, verbose_name='навык'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.DeleteModel(
            name='Candidate',
        ),
        migrations.DeleteModel(
            name='SkillGroup',
        ),
        migrations.AddField(
            model_name='skill',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='lk.tag'),
        ),
    ]
