# Generated by Django 4.0.4 on 2022-05-20 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0005_tag_remove_skill_group_remove_skill_text_skill_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='автор'),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.ManyToManyField(help_text='Введите навык', max_length=200, null=True, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tag',
            field=models.CharField(help_text='Введите название навыка', max_length=200, null=True, verbose_name='название навыка'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
