# Generated by Django 4.0.4 on 2022-05-20 14:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0006_alter_skill_candidate_remove_skill_skill_skill_skill_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.ManyToManyField(help_text='Введите навык', max_length=200, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
    ]
