# Generated by Django 4.0.4 on 2022-05-20 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0007_alter_skill_skill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skill',
            name='candidate',
        ),
        migrations.AddField(
            model_name='skill',
            name='candidate',
            field=models.ManyToManyField(help_text='Введите навык', max_length=200, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='skill',
            name='skill',
        ),
        migrations.AddField(
            model_name='skill',
            name='skill',
            field=models.CharField(help_text='Введите название навыка', max_length=200, null=True, verbose_name='название навыка'),
        ),
    ]
