# Generated by Django 4.0.4 on 2022-05-20 17:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lk', '0008_remove_skill_candidate_skill_candidate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='candidate',
            field=models.ManyToManyField(max_length=200, related_name='skills', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skill',
            field=models.CharField(max_length=200, null=True, verbose_name='название навыка'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='tag',
            field=models.CharField(max_length=200, null=True, verbose_name=' навык'),
        ),
    ]
