# Generated by Django 4.0.4 on 2022-05-21 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0011_rename_skill_skill_name_rename_tag_tag_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('tag', 'name')},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ('name',)},
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='candidates',
            new_name='candidate',
        ),
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='название навыка'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='tag'),
        ),
    ]
