# Generated by Django 4.0.4 on 2022-05-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0012_alter_skill_options_alter_tag_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='name',
            field=models.CharField(max_length=200, null=True, verbose_name='название навыка'),
        ),
        migrations.AlterUniqueTogether(
            name='skill',
            unique_together={('tag', 'name')},
        ),
    ]
